# docker-compose.yml
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "9090:9090"
    volumes:
      # Монтируем код для live-reload
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    # Используем 'air' для hot-reload в Go (нужно установить 'go install github.com/cosmtrek/air@latest')
    # Если 'air' не установлен, используйте: command: go run ./cmd/api
    command: air -c .air.toml

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: scoring_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: